version: "3.8"

services:
  mongo:
    build:
      context: ./mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: public-notes-app
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

volumes:
  mongo-data:
