apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
    maxconn 256
    log stdout format raw local0

    defaults
    mode http
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

    frontend http-in
    bind *:80
    default_backend flask_backends

    backend flask_backends
    balance roundrobin
    server app1 public-notes-app-1:80 check
    server app2 public-notes-app-2:80 check
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: ttruc09/public-notes-haproxy:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: haproxy-config-volume
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config-volume
          configMap:
            name: haproxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
