apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ttrinh.notes.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-notes-app-service
                port:
                  number: 80
